/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known/oauth-authorization-server'
import { Route as DotwellKnownOauthProtectedResourceRouteImport } from './routes/[.]well-known/oauth-protected-resource'
import { Route as ApiOpenapiDotjsonRouteImport } from './routes/api/openapi[.]json'
import { Route as OauthAuthorizeRouteImport } from './routes/oauth/authorize'
import { Route as OauthRevokeRouteImport } from './routes/oauth/revoke'
import { Route as OauthTokenRouteImport } from './routes/oauth/token'
import { Route as ApiMcpIndexRouteImport } from './routes/api/mcp/index'
import { Route as ApiMcpSplatRouteImport } from './routes/api/mcp/$'
import { Route as ApiMcpMessagesRouteImport } from './routes/api/mcp/messages'
import { Route as ApiMcpSseRouteImport } from './routes/api/mcp/sse'
import { Route as ApiCrmFiggyWebhookRouteImport } from './routes/api/crm/figgy/webhook'
import { Route as ApiMcpClientsPresetsRouteImport } from './routes/api/mcp/clients/presets'
import { Route as ApiMcpClientsIdSetupRouteImport } from './routes/api/mcp/clients/$id/setup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOauthProtectedResourceRoute =
  DotwellKnownOauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOpenapiDotjsonRoute = ApiOpenapiDotjsonRouteImport.update({
  id: '/api/openapi.json',
  path: '/api/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthAuthorizeRoute = OauthAuthorizeRouteImport.update({
  id: '/oauth/authorize',
  path: '/oauth/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthRevokeRoute = OauthRevokeRouteImport.update({
  id: '/oauth/revoke',
  path: '/oauth/revoke',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthTokenRoute = OauthTokenRouteImport.update({
  id: '/oauth/token',
  path: '/oauth/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpIndexRoute = ApiMcpIndexRouteImport.update({
  id: '/api/mcp/',
  path: '/api/mcp/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpSplatRoute = ApiMcpSplatRouteImport.update({
  id: '/api/mcp/$',
  path: '/api/mcp/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpMessagesRoute = ApiMcpMessagesRouteImport.update({
  id: '/api/mcp/messages',
  path: '/api/mcp/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpSseRoute = ApiMcpSseRouteImport.update({
  id: '/api/mcp/sse',
  path: '/api/mcp/sse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrmFiggyWebhookRoute = ApiCrmFiggyWebhookRouteImport.update({
  id: '/api/crm/figgy/webhook',
  path: '/api/crm/figgy/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpClientsPresetsRoute = ApiMcpClientsPresetsRouteImport.update({
  id: '/api/mcp/clients/presets',
  path: '/api/mcp/clients/presets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpClientsIdSetupRoute = ApiMcpClientsIdSetupRouteImport.update({
  id: '/api/mcp/clients/$id/setup',
  path: '/api/mcp/clients/$id/setup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/oauth/revoke': typeof OauthRevokeRoute
  '/oauth/token': typeof OauthTokenRoute
  '/api/mcp/$': typeof ApiMcpSplatRoute
  '/api/mcp/messages': typeof ApiMcpMessagesRoute
  '/api/mcp/sse': typeof ApiMcpSseRoute
  '/api/mcp/': typeof ApiMcpIndexRoute
  '/api/crm/figgy/webhook': typeof ApiCrmFiggyWebhookRoute
  '/api/mcp/clients/presets': typeof ApiMcpClientsPresetsRoute
  '/api/mcp/clients/$id/setup': typeof ApiMcpClientsIdSetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/oauth/revoke': typeof OauthRevokeRoute
  '/oauth/token': typeof OauthTokenRoute
  '/api/mcp/$': typeof ApiMcpSplatRoute
  '/api/mcp/messages': typeof ApiMcpMessagesRoute
  '/api/mcp/sse': typeof ApiMcpSseRoute
  '/api/mcp': typeof ApiMcpIndexRoute
  '/api/crm/figgy/webhook': typeof ApiCrmFiggyWebhookRoute
  '/api/mcp/clients/presets': typeof ApiMcpClientsPresetsRoute
  '/api/mcp/clients/$id/setup': typeof ApiMcpClientsIdSetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/oauth/revoke': typeof OauthRevokeRoute
  '/oauth/token': typeof OauthTokenRoute
  '/api/mcp/$': typeof ApiMcpSplatRoute
  '/api/mcp/messages': typeof ApiMcpMessagesRoute
  '/api/mcp/sse': typeof ApiMcpSseRoute
  '/api/mcp/': typeof ApiMcpIndexRoute
  '/api/crm/figgy/webhook': typeof ApiCrmFiggyWebhookRoute
  '/api/mcp/clients/presets': typeof ApiMcpClientsPresetsRoute
  '/api/mcp/clients/$id/setup': typeof ApiMcpClientsIdSetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/api/openapi.json'
    | '/oauth/authorize'
    | '/oauth/revoke'
    | '/oauth/token'
    | '/api/mcp/$'
    | '/api/mcp/messages'
    | '/api/mcp/sse'
    | '/api/mcp/'
    | '/api/crm/figgy/webhook'
    | '/api/mcp/clients/presets'
    | '/api/mcp/clients/$id/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/api/openapi.json'
    | '/oauth/authorize'
    | '/oauth/revoke'
    | '/oauth/token'
    | '/api/mcp/$'
    | '/api/mcp/messages'
    | '/api/mcp/sse'
    | '/api/mcp'
    | '/api/crm/figgy/webhook'
    | '/api/mcp/clients/presets'
    | '/api/mcp/clients/$id/setup'
  id:
    | '__root__'
    | '/'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/api/openapi.json'
    | '/oauth/authorize'
    | '/oauth/revoke'
    | '/oauth/token'
    | '/api/mcp/$'
    | '/api/mcp/messages'
    | '/api/mcp/sse'
    | '/api/mcp/'
    | '/api/crm/figgy/webhook'
    | '/api/mcp/clients/presets'
    | '/api/mcp/clients/$id/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  DotwellKnownOauthProtectedResourceRoute: typeof DotwellKnownOauthProtectedResourceRoute
  ApiOpenapiDotjsonRoute: typeof ApiOpenapiDotjsonRoute
  OauthAuthorizeRoute: typeof OauthAuthorizeRoute
  OauthRevokeRoute: typeof OauthRevokeRoute
  OauthTokenRoute: typeof OauthTokenRoute
  ApiMcpSplatRoute: typeof ApiMcpSplatRoute
  ApiMcpMessagesRoute: typeof ApiMcpMessagesRoute
  ApiMcpSseRoute: typeof ApiMcpSseRoute
  ApiMcpIndexRoute: typeof ApiMcpIndexRoute
  ApiCrmFiggyWebhookRoute: typeof ApiCrmFiggyWebhookRoute
  ApiMcpClientsPresetsRoute: typeof ApiMcpClientsPresetsRoute
  ApiMcpClientsIdSetupRoute: typeof ApiMcpClientsIdSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi.json': {
      id: '/api/openapi.json'
      path: '/api/openapi.json'
      fullPath: '/api/openapi.json'
      preLoaderRoute: typeof ApiOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/authorize': {
      id: '/oauth/authorize'
      path: '/oauth/authorize'
      fullPath: '/oauth/authorize'
      preLoaderRoute: typeof OauthAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/revoke': {
      id: '/oauth/revoke'
      path: '/oauth/revoke'
      fullPath: '/oauth/revoke'
      preLoaderRoute: typeof OauthRevokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/token': {
      id: '/oauth/token'
      path: '/oauth/token'
      fullPath: '/oauth/token'
      preLoaderRoute: typeof OauthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/': {
      id: '/api/mcp/'
      path: '/api/mcp'
      fullPath: '/api/mcp/'
      preLoaderRoute: typeof ApiMcpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/$': {
      id: '/api/mcp/$'
      path: '/api/mcp/$'
      fullPath: '/api/mcp/$'
      preLoaderRoute: typeof ApiMcpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/messages': {
      id: '/api/mcp/messages'
      path: '/api/mcp/messages'
      fullPath: '/api/mcp/messages'
      preLoaderRoute: typeof ApiMcpMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/sse': {
      id: '/api/mcp/sse'
      path: '/api/mcp/sse'
      fullPath: '/api/mcp/sse'
      preLoaderRoute: typeof ApiMcpSseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crm/figgy/webhook': {
      id: '/api/crm/figgy/webhook'
      path: '/api/crm/figgy/webhook'
      fullPath: '/api/crm/figgy/webhook'
      preLoaderRoute: typeof ApiCrmFiggyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/clients/presets': {
      id: '/api/mcp/clients/presets'
      path: '/api/mcp/clients/presets'
      fullPath: '/api/mcp/clients/presets'
      preLoaderRoute: typeof ApiMcpClientsPresetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/clients/$id/setup': {
      id: '/api/mcp/clients/$id/setup'
      path: '/api/mcp/clients/$id/setup'
      fullPath: '/api/mcp/clients/$id/setup'
      preLoaderRoute: typeof ApiMcpClientsIdSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  DotwellKnownOauthProtectedResourceRoute:
    DotwellKnownOauthProtectedResourceRoute,
  ApiOpenapiDotjsonRoute: ApiOpenapiDotjsonRoute,
  OauthAuthorizeRoute: OauthAuthorizeRoute,
  OauthRevokeRoute: OauthRevokeRoute,
  OauthTokenRoute: OauthTokenRoute,
  ApiMcpSplatRoute: ApiMcpSplatRoute,
  ApiMcpMessagesRoute: ApiMcpMessagesRoute,
  ApiMcpSseRoute: ApiMcpSseRoute,
  ApiMcpIndexRoute: ApiMcpIndexRoute,
  ApiCrmFiggyWebhookRoute: ApiCrmFiggyWebhookRoute,
  ApiMcpClientsPresetsRoute: ApiMcpClientsPresetsRoute,
  ApiMcpClientsIdSetupRoute: ApiMcpClientsIdSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
